---
title: "Mass_shooting_research"
author: "Min Jeong Oh"
date: "3/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```



```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(foreign)
library(dplyr)
library(ggplot2)
library(scales)
library(car)
library(arm)
library(tidyr)
```

```{r import data, message=FALSE, warning=FALSE, echo=FALSE}

# Read data
dataset = read.spss("/Users/minoh/Documents/Personal_Projects/Data/gss_spss_with_codebook/GSS7218_R3.sav", to.data.frame=TRUE)
shooting <- read.csv("/Users/minoh/Documents/Personal_Projects/Data/Mother Jones - Mass Shootings Database, 1982 - 2021 - Sheet1.csv")

big.dataset = dataset %>% 
  dplyr::select(YEAR, ID, CHILDS, AGE, AGEKDBRN,  EDUC, PAEDUC, MAEDUC, SPEDUC, COEDUC, CODEG, DEGREE, SEX, RACE, RES16, REG16, REGION, ATTRELIG, RELIGID,XNORCSIZ, RELID1, CATHID, PARTYID, INCOME, RINCOME, INCOME72, INCOME77, RINCOM77, INCOME82, RINCOM82, INCOME86, RINCOM86, INCOME91, RINCOM91, INCOME98, RINCOM98, INCOME06, RINCOM06, INCOME16, RINCOM16, POLVIEWS, POLVIEWY, POLVIEWX, NATCRIME, NATCRIMZ, CRIMIMP, CRIMINFO, CRIMFIRM, LAWIMP, LAWINFO, LAWFIRM, GUNLAW, GUNIMP, GUNINFO, GUNFIRM, GUN, GUNAGE, GUNNUM, OWNGUN, PISTOL, SHOTGUN, RIFLE, ROWNGUN, HGUNLAW, HGUNCRIM, GUNSALES, GUNSDRUG, SEMIGUNS, GUNS911, RIFLES50, OTHGUNS, GUNSDRNK, GUN, GUNNUM )
```

```{r make small dataset, message=FALSE, warning=FALSE, echo=FALSE}
small.dataset = big.dataset %>% 
  dplyr::select(YEAR, ID, AGE, SEX, RACE, EDUC, DEGREE, RES16, REG16, REGION, INCOME, PARTYID, GUNLAW, OWNGUN, ROWNGUN, GUN, GUNNUM)

```

```{r clean data, message=FALSE, warning=FALSE, echo=FALSE}
# GSS data
small.dataset = small.dataset[!(is.na(small.dataset$GUNLAW)),]

small.dataset$PARTY <- recode(small.dataset$PARTYID, "c('STRONG DEMOCRAT', 'NOT STR DEMOCRAT') = 'Democrat';
                          c('IND,NEAR DEM', 'INDEPENDENT', 'IND,NEAR REP') = 'Independent';
                          c('NOT STR REPUBLICAN', 'STRONG REPUBLICAN') = 'Republican';
                            'OTHER PARTY' = NA")
small.dataset$GUNSUPPORT <- as.numeric(as.character(recode(small.dataset$GUNLAW,
                                                         "'FAVOR' = 1;
                                                         'OPPOSE' = 0;
                                                         ")))

```


```{r GSS data exploration, message=FALSE, warning=FALSE, echo=FALSE}
# Group by year
support.proportions <- group_by(small.dataset, YEAR) %>% 
  mutate(Favor = mean(GUNLAW == 'FAVOR'), Oppose = mean(GUNLAW == 'OPPOSE'))

gunconrtolsupport.proportions <- group_by(small.dataset, YEAR) %>% 
  summarize(Favor = mean(GUNLAW == 'FAVOR', na.rm=TRUE), Oppose = mean(GUNLAW == 'OPPOSE', na.rm=TRUE))


# Group by year and gunlaw - calculate the proportion of each party in the total 'Favor' and 'Oppose' by year
party.proportions <- group_by(support.proportions, YEAR, GUNLAW) %>% 
  mutate(prop.democrat = mean(PARTY == 'Democrat', na.rm=TRUE), prop.independent = mean(PARTY == 'Independent', na.rm=TRUE), prop.republican = mean(PARTY == 'Republican', na.rm=TRUE))

# Group by year and party - calculate the proportion of 'Favor' and 'Oppose' in each party by year
eachparty.proportions <- group_by(party.proportions, YEAR, PARTY) %>% 
  summarize(Favor.party = mean(GUNLAW == 'FAVOR', na.rm=TRUE), Oppose.party = mean(GUNLAW == 'OPPOSE', na.rm=TRUE))
eachparty.proportions = eachparty.proportions[!(is.na(eachparty.proportions$PARTY)),]

# Favor/oppose people proportion
favor.data <- party.proportions[party.proportions$GUNLAW == 'FAVOR', ]
oppose.data <- party.proportions[party.proportions$GUNLAW == 'OPPOSE', ]

# Calculate party proportion
favor.data$Democrat <- favor.data$prop.democrat * favor.data$Favor
favor.data$Independent <- favor.data$prop.independent * favor.data$Favor
favor.data$Republican <- favor.data$prop.republican * favor.data$Favor
oppose.data$Democrat <- oppose.data$prop.democrat * oppose.data$Oppose
oppose.data$Independent <- oppose.data$prop.independent * oppose.data$Oppose
oppose.data$Republican <- oppose.data$prop.republican * oppose.data$Oppose

```


```{r plot GSS data variables, message=FALSE, warning=FALSE, echo=FALSE}
# By year
favor.oppose.byyear <- gather(support.proportions,
                           value = "Ratio",
                           key = "Gun_Control",
                           Favor, Oppose)
favor.oppose.byyear.small = favor.oppose.byyear %>% 
  dplyr::select(YEAR, Gun_Control, Ratio)

favor.oppose.groupby.year <- group_by(favor.oppose.byyear.small, YEAR, Gun_Control) %>% 
  summarize(Ratio = mean(Ratio))

# Stacked bar chart
ggplot(favor.oppose.groupby.year, aes(fill=Gun_Control, y=Ratio, x=YEAR)) + 
    geom_bar(position="stack", stat="identity")

```
```{r plot party data, message=FALSE, warning=FALSE, echo=FALSE}
# Party by year
favor.party.byyear <- gather(favor.data,
                           value = "Ratio",
                           key = "Favor_gun_control",
                           Democrat, Independent, Republican)

favor.party.byyear.small = favor.party.byyear %>% 
  dplyr::select(YEAR, Favor_gun_control, Ratio)

favor.party.groupby.year <- group_by(favor.party.byyear.small, YEAR, Favor_gun_control) %>% 
  summarize(Ratio = mean(Ratio))


# Stacked bar chart
ggplot(favor.party.groupby.year, aes(fill=Favor_gun_control, y=Ratio, x=YEAR)) + 
    geom_bar(position="stack", stat="identity")


```



```{r shootings data manipulation, message=FALSE, warning=FALSE, echo=FALSE}

massshootings.byyear <- group_by(shooting, year) %>% 
  summarize(total_victims = sum(total_victims), num_case = length(case))

colnames(gunconrtolsupport.proportions) <- c("year", "Favor", "Oppose")

favor.oppose.massshooting.byyear <- merge(x = gunconrtolsupport.proportions, y = massshootings.byyear, by = "year", all = TRUE)
#colnames(favor.oppose.massshooting.byyear) <- c("Year", "Favor", "Oppose", "Total_victims", "Num_of_cases")
favor.oppose.massshooting.byyear$Favor <- as.numeric(favor.oppose.massshooting.byyear$Favor)
favor.oppose.massshooting.byyear$Oppose <- as.numeric(favor.oppose.massshooting.byyear$Oppose)
favor.oppose.massshooting.byyear$year <- as.numeric(favor.oppose.massshooting.byyear$year)
favor.oppose.massshooting.byyear$Favor.scaled.for.victims <- (favor.oppose.massshooting.byyear$Favor -0.5) * 400
favor.oppose.massshooting.byyear$Favor.scaled.for.cases <- (favor.oppose.massshooting.byyear$Favor -0.2) * 20
```

```{r plot , message=FALSE, warning=FALSE, echo=FALSE}

p <- ggplot(na.omit(favor.oppose.massshooting.byyear))
  p <- p + geom_line(aes(x = year, y = total_victims, colour = "Total victims"))
  
  # adding the relative humidity data, transformed to match roughly the range of the temperature
  p <- p + geom_line(aes(x = year, y=Favor.scaled.for.victims, colour = "Favor ratio"))
  
  # now adding the secondary axis, following the example in the help file ?scale_y_continuous
  # and, very important, reverting the above transformation
  p <- p + scale_y_continuous(sec.axis = sec_axis(~./400 + 0.5, name = "Favor ratio"))
  
  # modifying colours and theme options
  p <- p + scale_colour_manual(values = c("blue", "red"))
  p <- p + labs(y = "Number of total victims",
                x = "Year",
                colour = "Parameter")
  p <- p + theme(legend.position = c(0.1, 0.8))
p


```

```{r plot , message=FALSE, warning=FALSE, echo=FALSE}

p <- ggplot(na.omit(favor.oppose.massshooting.byyear))
  p <- p + geom_line(aes(x = year, y = num_case, colour = "Number of cases"))
  
  # adding the relative humidity data, transformed to match roughly the range of the temperature
  p <- p + geom_line(aes(x = year, y=Favor.scaled.for.cases, colour = "Favor ratio"))
  
  # now adding the secondary axis, following the example in the help file ?scale_y_continuous
  # and, very important, reverting the above transformation
  p <- p + scale_y_continuous(sec.axis = sec_axis(~./20 + 0.2, name = "Favor ratio"))
  
  
  # modifying colours and theme options
  p <- p + scale_colour_manual(values = c("blue", "red"))
  p <- p + labs(y = "Number of mass shootings",
                x = "Year",
                colour = "Parameter")
  p <- p + theme(legend.position = c(0.2, 0.5))
p


```



```{r favor data by party , message=FALSE, warning=FALSE, echo=FALSE}
#Subset data by each party
democrat.favor.ratio <- eachparty.proportions[ which(eachparty.proportions$PARTY=='Democrat'), ]
independent.favor.ratio <- eachparty.proportions[which(eachparty.proportions$PARTY=='Independent'),]
republican.favor.ratio <- eachparty.proportions[which(eachparty.proportions$PARTY=='Republican'),]
```

```{r favor data by party , message=FALSE, warning=FALSE, echo=FALSE}
colnames(democrat.favor.ratio) <- c("year", "Party","Favor", "Oppose")
colnames(independent.favor.ratio) <- c("year", "Party", "Favor", "Oppose")
colnames(republican.favor.ratio) <- c("year", "Party", "Favor", "Oppose")

favor.oppose.massshooting.byyear.democrat <- merge(x = democrat.favor.ratio, y = massshootings.byyear, by = "year", all = TRUE)
favor.oppose.massshooting.byyear.democrat$Favor <- as.numeric(favor.oppose.massshooting.byyear.democrat$Favor)
favor.oppose.massshooting.byyear.democrat$Oppose <- as.numeric(favor.oppose.massshooting.byyear.democrat$Oppose)
favor.oppose.massshooting.byyear.democrat$year <- as.numeric(favor.oppose.massshooting.byyear.democrat$year)
favor.oppose.massshooting.byyear.democrat$Favor.scaled <- (favor.oppose.massshooting.byyear.democrat$Favor -0.5) * 400

favor.oppose.massshooting.byyear.independent <- merge(x = independent.favor.ratio, y = massshootings.byyear, by="year", all=TRUE)
favor.oppose.massshooting.byyear.independent$Favor <- as.numeric(favor.oppose.massshooting.byyear.independent$Favor)
favor.oppose.massshooting.byyear.independent$Oppose <- as.numeric(favor.oppose.massshooting.byyear.independent$Oppose)
favor.oppose.massshooting.byyear.independent$year <- as.numeric(favor.oppose.massshooting.byyear.independent$year)
favor.oppose.massshooting.byyear.independent$Favor.scaled <- (favor.oppose.massshooting.byyear.independent$Favor -0.5) * 400

favor.oppose.massshooting.byyear.republican <- merge(x = republican.favor.ratio, y = massshootings.byyear, by="year", all=TRUE)
favor.oppose.massshooting.byyear.republican$Favor <- as.numeric(favor.oppose.massshooting.byyear.republican$Favor)
favor.oppose.massshooting.byyear.republican$Oppose <- as.numeric(favor.oppose.massshooting.byyear.republican$Oppose)
favor.oppose.massshooting.byyear.republican$year <- as.numeric(favor.oppose.massshooting.byyear.republican$year)
favor.oppose.massshooting.byyear.republican$Favor.scaled <- (favor.oppose.massshooting.byyear.republican$Favor -0.5) * 400


```

```{r plot mass shooting data with party data, message=FALSE, warning=FALSE, echo=FALSE}
p <- ggplot(na.omit(favor.oppose.massshooting.byyear.democrat))
  p <- p + geom_line(aes(x = year, y = total_victims, colour = "Total victims"))
  
  # adding the relative humidity data, transformed to match roughly the range of the temperature
  p <- p + geom_line(aes(x = year, y=Favor.scaled, colour = "Favor"))
  
  # now adding the secondary axis, following the example in the help file ?scale_y_continuous
  # and, very important, reverting the above transformation
  p <- p + scale_y_continuous(sec.axis = sec_axis(~./400 + 0.5, name = "Favor ratio"))
  
  # modifying colours and theme options
  p <- p + scale_colour_manual(values = c("blue", "red"))
  p <- p + labs(y = "Number of total victims",
                x = "Year",
                colour = "Parameter")
  p <- p + theme(legend.position = c(0.1, 0.8))
p

```

```{r plot mass shooting data with party data, message=FALSE, warning=FALSE, echo=FALSE}
p <- ggplot(na.omit(favor.oppose.massshooting.byyear.independent))
  p <- p + geom_line(aes(x = year, y = total_victims, colour = "Total victims"))
  
  # adding the relative humidity data, transformed to match roughly the range of the temperature
  p <- p + geom_line(aes(x = year, y=Favor.scaled, colour = "Favor"))
  
  # now adding the secondary axis, following the example in the help file ?scale_y_continuous
  # and, very important, reverting the above transformation
  p <- p + scale_y_continuous(sec.axis = sec_axis(~./400 + 0.5, name = "Favor ratio"))
  
  # modifying colours and theme options
  p <- p + scale_colour_manual(values = c("blue", "red"))
  p <- p + labs(y = "Number of total victims",
                x = "Year",
                colour = "Parameter")
  p <- p + theme(legend.position = c(0.1, 0.8))
p

```
```{r plot mass shooting data with party data, message=FALSE, warning=FALSE, echo=FALSE}
p <- ggplot(na.omit(favor.oppose.massshooting.byyear.republican))
  p <- p + geom_line(aes(x = year, y = total_victims, colour = "Total victims"))
  
  # adding the relative humidity data, transformed to match roughly the range of the temperature
  p <- p + geom_line(aes(x = year, y=Favor.scaled, colour = "Favor"))
  
  # now adding the secondary axis, following the example in the help file ?scale_y_continuous
  # and, very important, reverting the above transformation
  p <- p + scale_y_continuous(sec.axis = sec_axis(~./400 + 0.5, name = "Favor ratio"))
  
  # modifying colours and theme options
  p <- p + scale_colour_manual(values = c("blue", "red"))
  p <- p + labs(y = "Number of total victims",
                x = "Year",
                colour = "Parameter")
  p <- p + theme(legend.position = c(0.1, 0.8))
p

```




```{r model 1, message=FALSE, warning=FALSE, echo=FALSE}

favor.oppose.massshooting.byyear$z.favor <- scale(favor.oppose.massshooting.byyear$Favor,
       scale = (sd(favor.oppose.massshooting.byyear$Favor, na.rm=TRUE)*2)
       )
favor.oppose.massshooting.byyear$z.victims <- scale(favor.oppose.massshooting.byyear$total_victims,
       scale = (sd(favor.oppose.massshooting.byyear$total_victims, na.rm=TRUE)*2)
       )
favor.oppose.massshooting.byyear$z.numcase <- scale(favor.oppose.massshooting.byyear$num_case,
       scale = (sd(favor.oppose.massshooting.byyear$num_case, na.rm=TRUE)*2)
       )
gunsupport.model1 <- lm(z.favor ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear)
```

```{r model 2, message=FALSE, warning=FALSE, echo=FALSE}

favor.oppose.massshooting.byyear['z.favor.pushed'] <- c(favor.oppose.massshooting.byyear[-1 , 8], NA)
gunsupport.model2 <- lm(z.favor.pushed ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear)

library(jtools)
export_summs(gunsupport.model1, gunsupport.model2,
model.names = c("Model 1","Model 2"),
scale = TRUE, robust = TRUE)

effect_plot(gunsupport.model1, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
#export_summs(gunsupport.model5)
effect_plot(gunsupport.model2, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
```


```{r model 3, message=FALSE, warning=FALSE, echo=FALSE}
#model 3 with Democrat data
favor.oppose.massshooting.byyear.democrat$z.favor <- scale(favor.oppose.massshooting.byyear.democrat$Favor,
       scale = (sd(favor.oppose.massshooting.byyear.democrat$Favor, na.rm=TRUE)*2)
       )
favor.oppose.massshooting.byyear.democrat$z.victims <- scale(favor.oppose.massshooting.byyear.democrat$total_victims,
       scale = (sd(favor.oppose.massshooting.byyear.democrat$total_victims, na.rm=TRUE)*2)
       )
favor.oppose.massshooting.byyear.democrat$z.numcase <- scale(favor.oppose.massshooting.byyear.democrat$num_case,
       scale = (sd(favor.oppose.massshooting.byyear.democrat$num_case, na.rm=TRUE)*2)
       )
gunsupport.model3 <- lm(z.favor ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.democrat)


```

```{r model 4, message=FALSE, warning=FALSE, echo=FALSE}
#model 4 with Democrat pushed data
favor.oppose.massshooting.byyear.democrat['z.favor.pushed'] <- c(favor.oppose.massshooting.byyear.democrat[-1, 8], NA)
gunsupport.model4 <- lm(z.favor.pushed ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.democrat)

export_summs(gunsupport.model3, gunsupport.model4,
model.names = c("Model 3","Model 4"),
scale = TRUE, robust = TRUE)

effect_plot(gunsupport.model3, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model4, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")

```


```{r model 5, message=FALSE, warning=FALSE, echo=FALSE}
#model 5 with independent data
favor.oppose.massshooting.byyear.independent$z.favor <- scale(favor.oppose.massshooting.byyear.independent$Favor,
       scale = (sd(favor.oppose.massshooting.byyear.independent$Favor, na.rm=TRUE)*2)
       )
favor.oppose.massshooting.byyear.independent$z.victims <- scale(favor.oppose.massshooting.byyear.independent$total_victims,
       scale = (sd(favor.oppose.massshooting.byyear.independent$total_victims, na.rm=TRUE)*2)
       )
favor.oppose.massshooting.byyear.independent$z.numcase <- scale(favor.oppose.massshooting.byyear.independent$num_case,
       scale = (sd(favor.oppose.massshooting.byyear.independent$num_case, na.rm=TRUE)*2)
       )
gunsupport.model5 <- lm(z.favor ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.independent)


```

```{r model 6, message=FALSE, warning=FALSE, echo=FALSE}
favor.oppose.massshooting.byyear.independent['z.favor.pushed'] <- c(favor.oppose.massshooting.byyear.independent[-1, 8], NA)
gunsupport.model6 <- lm(z.favor.pushed ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.independent)

export_summs(gunsupport.model5, gunsupport.model6,
model.names = c("Model 5","Model 6"),
scale = TRUE, robust = TRUE)

effect_plot(gunsupport.model5, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
#export_summs(gunsupport.model5)
effect_plot(gunsupport.model6, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")

```

```{r model 7, message=FALSE, warning=FALSE, echo=FALSE}
#model 7 with republican data
favor.oppose.massshooting.byyear.republican$z.favor <- scale(favor.oppose.massshooting.byyear.republican$Favor,
       scale = (sd(favor.oppose.massshooting.byyear.republican$Favor, na.rm=TRUE)*2)
       )
favor.oppose.massshooting.byyear.republican$z.victims <- scale(favor.oppose.massshooting.byyear.republican$total_victims,
       scale = (sd(favor.oppose.massshooting.byyear.republican$total_victims, na.rm=TRUE)*2)
       )
favor.oppose.massshooting.byyear.republican$z.numcase <- scale(favor.oppose.massshooting.byyear.republican$num_case,
       scale = (sd(favor.oppose.massshooting.byyear.republican$num_case, na.rm=TRUE)*2)
       )
gunsupport.model7 <- lm(z.favor ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.republican)


```

```{r model 8, message=FALSE, warning=FALSE, echo=FALSE}
favor.oppose.massshooting.byyear.republican['z.favor.pushed'] <- c(favor.oppose.massshooting.byyear.republican[-1, 8], NA)
gunsupport.model8 <- lm(z.favor.pushed ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.republican)

export_summs(gunsupport.model7, gunsupport.model8,
model.names = c("Model 7","Model 8"),
scale = TRUE, robust = TRUE)

effect_plot(gunsupport.model7, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
#export_summs(gunsupport.model5)
effect_plot(gunsupport.model8, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")

```


```{r testing removing outliers}
#democrat
favor.oppose.massshooting.byyear.democrat.before.2012 = favor.oppose.massshooting.byyear.democrat[which(favor.oppose.massshooting.byyear.democrat$year < 2012), ]
gunsupport.model9 <- lm(z.favor ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.democrat.before.2012)
gunsupport.model10 <- lm(z.favor.pushed ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.democrat.before.2012)

export_summs(gunsupport.model9, gunsupport.model10,
model.names = c("Model 9","Model 10"),
scale = TRUE, robust = TRUE)


effect_plot(gunsupport.model9, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model9, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model10, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model10, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")

#independent
favor.oppose.massshooting.byyear.independent.before.2012 = favor.oppose.massshooting.byyear.independent[which(favor.oppose.massshooting.byyear.independent$year < 2012), ]
gunsupport.model11 <- lm(z.favor ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.independent.before.2012)
gunsupport.model12 <- lm(z.favor.pushed ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.independent.before.2012)

export_summs(gunsupport.model11, gunsupport.model12,
model.names = c("Model 11","Model 12"),
scale = TRUE, robust = TRUE)

effect_plot(gunsupport.model11, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model11, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model12, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model12, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")


#republican
favor.oppose.massshooting.byyear.republican.before.2012 = favor.oppose.massshooting.byyear.republican[which(favor.oppose.massshooting.byyear.republican$year < 2012), ]
gunsupport.model13 <- lm(z.favor ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.republican.before.2012)
gunsupport.model14 <- lm(z.favor.pushed ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.republican.before.2012)

export_summs(gunsupport.model13, gunsupport.model14,
model.names = c("Model 13","Model 14"),
scale = TRUE, robust = TRUE)

effect_plot(gunsupport.model13, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model13, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model14, pred = z.victims, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model14, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
```


```{r residual plot}
#gunsupport.model7 <- lm(z.favor ~ z.victims + z.numcase, data = favor.oppose.massshooting.byyear.republican)

model7.res = resid(gunsupport.model7)
plot(fitted(gunsupport.model7), model7.res)
abline(0, 0)                  # the horizon
```

```{r 1 explanatory variable}
gunsupport.model15 <- lm(z.favor ~ z.numcase, data = favor.oppose.massshooting.byyear)

gunsupport.model16 <- lm(z.favor.pushed ~ z.numcase, data = favor.oppose.massshooting.byyear)

export_summs(gunsupport.model15, gunsupport.model16,
model.names = c("Model 15","Model 16"),
scale = TRUE, robust = TRUE)

effect_plot(gunsupport.model15, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model16, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
```
```{r model 17, 18, message=FALSE, warning=FALSE, echo=FALSE}
#Democrat data

gunsupport.model17 <- lm(z.favor ~ z.numcase, data = favor.oppose.massshooting.byyear.democrat)
gunsupport.model18 <- lm(z.favor.pushed ~ z.numcase, data = favor.oppose.massshooting.byyear.democrat)

export_summs(gunsupport.model17, gunsupport.model18,
model.names = c("Model 17","Model 18"),
scale = TRUE, robust = TRUE)

effect_plot(gunsupport.model17, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model18, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")

```
```{r model 19, 20, message=FALSE, warning=FALSE, echo=FALSE}
#independent data

gunsupport.model19 <- lm(z.favor ~ z.numcase, data = favor.oppose.massshooting.byyear.independent)
gunsupport.model20 <- lm(z.favor.pushed ~ z.numcase, data = favor.oppose.massshooting.byyear.independent)

export_summs(gunsupport.model19, gunsupport.model20,
model.names = c("Model 19","Model 20"),
scale = TRUE, robust = TRUE)

effect_plot(gunsupport.model19, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
#export_summs(gunsupport.model5)
effect_plot(gunsupport.model20, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")

```
```{r model 21, 22, message=FALSE, warning=FALSE, echo=FALSE}
#republican data
gunsupport.model21 <- lm(z.favor ~ z.numcase, data = favor.oppose.massshooting.byyear.republican)
gunsupport.model22 <- lm(z.favor.pushed ~ z.numcase, data = favor.oppose.massshooting.byyear.republican)

export_summs(gunsupport.model21, gunsupport.model22,
model.names = c("Model 21","Model 22"),
scale = TRUE, robust = TRUE)

effect_plot(gunsupport.model21, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")
effect_plot(gunsupport.model22, pred = z.numcase, interval = TRUE, plot.points = TRUE,
            robust = "HC3")

```


\vspace{6mm}

